// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlcsU7Vk-8JgLLqYzTRtIsbwgwyWAJX10',
    appId: '1:1043763935492:web:60c2e2d5b55cfc54977851',
    messagingSenderId: '1043763935492',
    projectId: 'dos1-23caf',
    authDomain: 'dos1-23caf.firebaseapp.com',
    databaseURL: 'https://dos1-23caf-default-rtdb.firebaseio.com',
    storageBucket: 'dos1-23caf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtx2bIXkW0oN7l9G_-olsyOnkmxFWFLSk',
    appId: '1:1043763935492:android:62a7fa570200ddcf977851',
    messagingSenderId: '1043763935492',
    projectId: 'dos1-23caf',
    databaseURL: 'https://dos1-23caf-default-rtdb.firebaseio.com',
    storageBucket: 'dos1-23caf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOzAgOod1eGFP4lKj7n2eYFWlM2OKgs9c',
    appId: '1:1043763935492:ios:c88a54c1f9adffc5977851',
    messagingSenderId: '1043763935492',
    projectId: 'dos1-23caf',
    databaseURL: 'https://dos1-23caf-default-rtdb.firebaseio.com',
    storageBucket: 'dos1-23caf.appspot.com',
    iosBundleId: 'com.example.spindleDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOzAgOod1eGFP4lKj7n2eYFWlM2OKgs9c',
    appId: '1:1043763935492:ios:c88a54c1f9adffc5977851',
    messagingSenderId: '1043763935492',
    projectId: 'dos1-23caf',
    databaseURL: 'https://dos1-23caf-default-rtdb.firebaseio.com',
    storageBucket: 'dos1-23caf.appspot.com',
    iosBundleId: 'com.example.spindleDash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlcsU7Vk-8JgLLqYzTRtIsbwgwyWAJX10',
    appId: '1:1043763935492:web:f377507255d17144977851',
    messagingSenderId: '1043763935492',
    projectId: 'dos1-23caf',
    authDomain: 'dos1-23caf.firebaseapp.com',
    databaseURL: 'https://dos1-23caf-default-rtdb.firebaseio.com',
    storageBucket: 'dos1-23caf.appspot.com',
  );
}
